import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Provider";
import { LoadingProvider } from "@/components/loadingPage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <LoadingProvider loading={false}>{children}</LoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
